name: Deploy to EC2
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync content folder to EC2 
        uses: burnett01/rsync-deploy@v1.1
        with:
          switches: "-avz --delete"
          path: "content/"
          remote_path: "/home/ec2-user/content"
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: "ec2-user"
          remote_key: ${{ secrets.EC2_KEY }}

      - name: Install dependencies & Restart PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/content/backend
            npm install --production
            pm2 restart all
